### ISSUE TITLE
Checkpoint #3 Task list due October 15th

### ISSUE THREAD

**Issue by JeremyF5737** [JeremyF5737/Elder_Scrolls_Morrowind_Books#13]
- [x] Design website layout 

- [x] Meeting on updating RelaxNG schema @everyone

- [x] txt files from morrowind books

- [x]  make a list of authors from morrowind books @Tricky-Keys @ebeshero 

- [x]  Make a Schematron - @ebeshero

**Comment by ebeshero** [comment]
The list of authors is here: https://github.com/JeremyF5737/Elder_Scrolls/blob/master/authors.xml 
Does it look about right? This is all the distinct-values of authors names in that Wiki page we were looking at on Friday (removing repeats).
