### ISSUE TITLE
Task List Week 1 of project (due October 2nd) 

### ISSUE THREAD

**Issue by JeremyF5737** [JeremyF5737/Elder_Scrolls_Morrowind_Books#5]
@Joelpie @Tricky-Keys 

- [x] Separate duplicate books (@Tricky-Keys )

- [x] separate game-exclusive books to separate folders (@JeremyF5737 )

- [x] make an xml example for a book and discuss relaxNG (Everyone)

- [x]  RelaxNG (@Joelpie)
